iso:
  stage: deploy
  image: nixos/nix
  script:
    - nix-build '<nixpkgs/nixos>' -A config.system.build.isoImage -I nixos-config=iso.nix
  artifacts:
    paths:
      - public
  only:
    - master
